### ISSUE TITLE
Data - No Acc. ID - Liu et al. 2006

### ISSUE THREAD

**Issue by gadenbuie** [tgerke/curatedProstateData#5]
Source: ArrayExpress
 
```yaml
label: Liu et al. 2006
size:
  'n': 57
platform:
- name: Affy U133
link:
  primary: https://www.ebi.ac.uk/arrayexpress/experiments/E-TABM-26/
accession: No Acc. ID

```
